apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nats-cert
  namespace: bb
spec:
  dnsNames:
  - appscode.ninja
  - nats.appscode.ninja
  - grafana.appscode.ninja
  - prometheus.appscode.ninja
  - console.appscode.ninja
  - kubedb.appscode.ninja
  - deploy.appscode.ninja
  - marketplace.appscode.ninja
  issuerRef:
    group: cert-manager.io
    kind: Issuer
    name: bytebuilders
  secretName: bytebuilders-cert
  usages:
  - digital signature
  - key encipherment
